# Generated by Django 4.2.2 on 2023-07-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_first_name_customer_filial_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
