# Generated by Django 4.2.2 on 2023-08-12 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0002_rename_product_brand_productmodel_product_brands_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='damaged_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='exported_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='involved_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='involved',
            field=models.BooleanField(default=False),
        ),
    ]
