# Generated by Django 4.2.2 on 2023-08-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbar', '0004_product_sale_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
